---

- hosts: Centos
  user: "{{ user }}"
  tasks:

    - name: Run sleep.sh
      command: "/home/{{ user }}/sleep.sh"
      async: 60
      poll: 0
      delegate_to: localhost
    - name: Install mariadb
      package:
        name: mariadb
        state: latest
      become: yes
