---

- hosts: Centos
  user: "{{ user }}"
  vars_files:
    - vars.yml
  tasks:

    - name: Check_services
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ service_list }}"
