---

- hosts: Centos
  user: "{{ user }}"
  vars_files:
    - /home/varun/Documents/aws_security/ansible/vault
  tasks:

    - name: Add secret test to open.txt
      lineinfile:
        path: "/home/{{ user }}/open.txt"
        create: yes
        line: "{{ password }}"
      no_log: true
