---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"  
      state: present
      update_cache: yes

  - name: Start the apache2 service
    systemd:
      name: "{{ apached_package }}"
      state: started
      enabled: yes
 

